GET http://localhost:8880/ebook/list?page=1&size=100

###

GET http://localhost:8880/ebook/all

###

POST http://localhost:8880/ebook/save?id=1&category1Id=23

###

DELETE http://localhost:8880/ebook/delete/423129729537806336

###

GET http://localhost:8880/category/list